### ISSUE TITLE
Dev-Log #2 Issue/Improvement reported so far

### ISSUE THREAD

**Issue by Paul-Charpentier** [Paul-Charpentier/SPCAndie#2]
Here are some issue and improvement that have been reported so far and improvement that are needed: 

- [x] [ISSUE] Possible night bin that missing after night binning
- [ ] [IMPROVEMENT] BERV correction (see #1 )
- [x] [ISSUE] the wrong PCA components are saved (fixed by saving `pca_component[:10]` instead of `pcomp`)
- [x] [IMPROVEMENT] as mentioned in #1 , Replace the first brutal sigma clipping to remove outliers by something more accurate
- [ ] [IMPROVEMENT] as mentioned in #1 , Improve the outliers removal in the PCA by a true robust method (maybe switch to the full _wapiti_ method (Ould-Elhkim et al. 2023) instead of our "proto-_wapiti_" method)  
- [ ] [CHECK] Vertical VS Horizontal standardization
- [ ] [CHECK] Redoing standardization before each PCA

**Comment by Paul-Charpentier** [comment]
Issue fixed ;) 
Still have to work on inprovement

**Comment by Paul-Charpentier** [comment]
Full __wapiti__-ing doesn't seem to be adapted to our problem so far

**Comment by Paul-Charpentier** [comment]
I've replaced our weird sigma clipping by a true one using `astropy.stats.sigma_clip()`

**Comment by Paul-Charpentier** [comment]
Following SPIRou-LBL users meeting Here is a list of new things to check/do : 

- [ ] [CHECK] Use Vtot instead of BERV
- [ ] [CHECK] Who are the lines that are the most impacted by the BERV issue
- [ ] [CHECK] Try to mask remaining BERV features after filering
- [ ] [FEATURE] Wask filtered points in RVs data at the same time as dLWs 
- [ ] [CHECK] Use Templates that are not the target itself

**Comment by Paul-Charpentier** [comment]
- Masking the remaining BERV features is facing the same issue that we've seen with `0.3.1` version which is that once we mask those features, we have to re-compute the PCA. Doing this, the PCA is recalibrated and new features pops up and so on and so one... 
- I've implemented the feature to mask filtered points in RV data. So far it doesn't seem to improve the correlation between RVs and W1 or its first derivative

**Comment by Paul-Charpentier** [comment]
Concerning the identification of impacted lines, Here is an idea that sounds promising: 

One can deflect one _wapiti_ feature that is able to identify the most active lines (The lines with the biggest score regarding the component showing activity features) tho make it identify the most "BERVed" lines (and filter it afterward)

One could do this while looking only at the region where BERV is the most correlated with W1 as well

**Comment by Paul-Charpentier** [comment]
Here are the results for all reference stars + some studied stars for both of the _APERO_/_lbl_ pipeline versions
![W1ZP](https://user-images.githubusercontent.com/86246436/233116924-17dafe84-d5d2-4413-8496-68f62fd7b631.gif)
What we can see is that it doesn't seem to have "Zero-Point" systematics in _W1_ even if some pairs of stars seems to follow the same pattern (Gl725A-EV_Lac; Gj1002-Gj1286; etc)

**Comment by Paul-Charpentier** [comment]
Almost no changes while using Gl905 as a template for Gj1289 instead of Gj1289 itself. 
Still have to look for the others targets
